### ISSUE TITLE
OpenAPI Validation is case sensitive with header names

### ISSUE THREAD

**Issue by miklish** [networknt/light-rest-4j#122]
The `ParameterDeserializer` class in the `openapi-meta` module of light-rest-4j uses a case sensitive lookup to determine how to deserialize header values. This violates [RFC 7230](https://tools.ietf.org/html/rfc7230#section-3.2) which states that header names are case insensitive.

E.g.: Consider the following header definition:

```yaml
- in: header
  name: myHeader
  schema:
    type: array
    items:
      type: string
      maxLength: 10       
```

E.g.: Assume a request occurs in where the following header and value are sent

`myheader: 123,456,789`

The deserializer will not deserialize this into an array of 3 3-character strings since it does not find the appropriate deserialization method for 'myheader'. Instead, it will leave it as a single 11-character string. The validator will then throw an error saying that length of the header exceeds 10 characters.
