### ISSUE TITLE
Scope verification doesnot work with two or more securitySchemes

### ISSUE THREAD

**Issue by stevehu** [networknt/light-rest-4j#136]
While working with UK OpenBanking Account API, it has two securitySchemes defined as below.

```
  securitySchemes:
    TPPOAuth2Security:
      type: oauth2
      description: TPP client credential authorisation flow with the ASPSP
      flows:
        clientCredentials:
          tokenUrl: 'https://authserver.example/token'
          scopes:
            accounts: Ability to read Accounts information
    PSUOAuth2Security:
      type: oauth2
      description: >-
        OAuth flow, it is required when the PSU needs to perform SCA with the
        ASPSP when a TPP wants to access an ASPSP resource owned by the PSU
      flows:
        authorizationCode:
          authorizationUrl: 'https://authserver.example/authorization'
          tokenUrl: 'https://authserver.example/token'
          scopes:
            accounts: Ability to read Accounts information

```

The OpenAPIHelper implementation assumes that there is only one securityScheme available in the spec and it works well until now. As you know, we are loading the openapi.yaml at runtime to verify the scopes based on the specification and we are using the scheme name to lookup the scopes. With the above spec, if PSUOauth2Security is used, we cannot get the scopes and scope verification fails. To fix it, we need to allow multiple schemes in the spec and put them into an array list. When lookup the scopes, we need to iterate all the schemes in the array to find the scopes.
