### ISSUE TITLE
schema validation does not work for boolean query parameter

### ISSUE THREAD

**Issue by stevehu** [networknt/light-rest-4j#57]
The OpenAPI spec defines a boolean type parameter:

```
     parameters:
      - name: redirect
        in: query
        required: false
        description: Whether or not to do a redirect. >
          If true the response will contain 302 Status and a Location header with new URL.
        schema:
          type: boolean
```
when I call {{ADDRESS}}/v2/translate/some-id?redirect=false I get the error:

```
{"statusCode":400,"code":"ERR11004","message":"VALIDATOR_SCHEMA","description":"Schema Validation Error - $: string found, boolean expected","severity":"ERROR"}
```
