### ISSUE TITLE
oneOf schema validation does not work

### ISSUE THREAD

**Issue by stevehu** [networknt/light-rest-4j#58]
An endpoint  takes a string or integer throwing a validation error:

```
      parameters:
      - name: id
        in: path
        description: ID or GID
        required: true
        schema:
          oneOf:
          - type: integer
            format: int64
          - type: string
```

```
{"statusCode":400,"code":"ERR11004","message":"VALIDATOR_SCHEMA","description":"Schema Validation Error - $: should be valid to one and only one of the schemas ","severity":"ERROR"}
```
